// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZajKPixPsCD612YktQXr7r474jsjbhSk',
    appId: '1:17679102985:web:de7578013d6755fa3f34d8',
    messagingSenderId: '17679102985',
    projectId: 'pantry-buddy-2024',
    authDomain: 'pantry-buddy-2024.firebaseapp.com',
    databaseURL: 'https://pantry-buddy-2024-default-rtdb.firebaseio.com/',
    storageBucket: 'pantry-buddy-2024.appspot.com',
    measurementId: 'G-8EW6VJYGVX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtnumc8hq5y07i_0ha6GdlzP1vWkfaK1U',
    appId: '1:17679102985:android:cc7e1e136a9e8e7b3f34d8',
    messagingSenderId: '17679102985',
    projectId: 'pantry-buddy-2024',
    databaseURL: 'https://pantry-buddy-2024-default-rtdb.firebaseio.com/',
    storageBucket: 'pantry-buddy-2024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDH_ZjlutLjXLABHhJ805EeBEBNQ58g6ME',
    appId: '1:17679102985:ios:ffac8886ac2c66153f34d8',
    messagingSenderId: '17679102985',
    projectId: 'pantry-buddy-2024',
    databaseURL: 'https://pantry-buddy-2024-default-rtdb.firebaseio.com/',
    storageBucket: 'pantry-buddy-2024.appspot.com',
    iosBundleId: 'com.a11.pantrybuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDH_ZjlutLjXLABHhJ805EeBEBNQ58g6ME',
    appId: '1:17679102985:ios:76ab4993f638c0743f34d8',
    messagingSenderId: '17679102985',
    projectId: 'pantry-buddy-2024',
    databaseURL: 'https://pantry-buddy-2024-default-rtdb.firebaseio.com/',
    storageBucket: 'pantry-buddy-2024.appspot.com',
    iosBundleId: 'com.a11.pantrybuddy.RunnerTests',
  );
}
